#!/usr/bin/env python3
"""
Example script for analyzing vehicle zone duration data

This script demonstrates how to work with the .durations.json files
generated by the automation pipeline.

Usage:
    python examples/analyze_vehicle_durations.py vehicle_durations_all.json
    python examples/analyze_vehicle_durations.py video.durations.json
"""

import json
import sys
from pathlib import Path
from collections import defaultdict
from typing import Dict, List


def load_duration_data(file_path: Path) -> Dict:
    """Load duration data from JSON file"""
    with open(file_path, 'r') as f:
        return json.load(f)


def analyze_single_video(data: Dict) -> None:
    """Analyze duration data from a single video"""

    metadata = data.get('metadata', {})
    vehicles = data.get('vehicles', {})
    summary = data.get('summary', {})

    print(f"\n{'=' * 70}")
    print(f"Video Analysis: {metadata.get('filename', 'Unknown')}")
    print(f"{'=' * 70}")
    print(f"Camera: {metadata.get('camera', 'Unknown')}")
    print(f"Date/Time: {metadata.get('datetime', 'Unknown')}")
    print(f"Duration: {metadata.get('duration_seconds', 0):.1f} seconds")
    print(f"\nTotal Vehicles Tracked: {summary.get('total_vehicles', 0)}")

    # Vehicles per zone
    print(f"\nVehicles per Zone:")
    for zone, count in summary.get('vehicles_per_zone', {}).items():
        print(f"  {zone}: {count}")

    # Vehicle class distribution
    print(f"\nVehicle Classes:")
    class_counts = defaultdict(int)
    for vehicle_data in vehicles.values():
        class_counts[vehicle_data['class_name']] += 1

    for class_name, count in sorted(class_counts.items()):
        print(f"  {class_name}: {count}")

    # Average dwell time per zone
    print(f"\nAverage Dwell Time per Zone (seconds):")
    zone_dwell_times = defaultdict(list)

    for vehicle_data in vehicles.values():
        for zone_name, visits in vehicle_data['zones'].items():
            for visit in visits:
                if visit['duration'] is not None:
                    zone_dwell_times[zone_name].append(visit['duration'])

    for zone_name, dwell_times in sorted(zone_dwell_times.items()):
        if dwell_times:
            avg_dwell = sum(dwell_times) / len(dwell_times)
            min_dwell = min(dwell_times)
            max_dwell = max(dwell_times)
            print(f"  {zone_name}:")
            print(f"    Average: {avg_dwell:.2f}s")
            print(f"    Min: {min_dwell:.2f}s")
            print(f"    Max: {max_dwell:.2f}s")
            print(f"    Samples: {len(dwell_times)}")

    # Zone visit sequences
    print(f"\nZone Visit Sequences (top 10 vehicles):")
    for i, (vehicle_id, vehicle_data) in enumerate(list(vehicles.items())[:10], 1):
        zones_visited = list(vehicle_data['zones'].keys())
        print(f"  Vehicle {vehicle_id} ({vehicle_data['class_name']}): {' -> '.join(zones_visited)}")


def analyze_consolidated_data(data: Dict) -> None:
    """Analyze consolidated duration data from multiple videos"""

    print(f"\n{'=' * 70}")
    print(f"Consolidated Analysis")
    print(f"{'=' * 70}")
    print(f"Files Processed: {data.get('files_processed', 0)}")
    print(f"Total Vehicles Tracked: {data.get('total_vehicles_tracked', 0)}")

    videos = data.get('videos', [])

    # Overall statistics
    all_zone_counts = defaultdict(int)
    all_class_counts = defaultdict(int)
    all_dwell_times = defaultdict(list)
    videos_by_camera = defaultdict(int)

    for video in videos:
        metadata = video.get('metadata', {})
        vehicles = video.get('vehicles', {})
        summary = video.get('summary', {})

        # Count by camera
        camera = metadata.get('camera', 'Unknown')
        videos_by_camera[camera] += 1

        # Zone counts
        for zone, count in summary.get('vehicles_per_zone', {}).items():
            all_zone_counts[zone] += count

        # Class counts
        for vehicle_data in vehicles.values():
            all_class_counts[vehicle_data['class_name']] += 1

        # Dwell times
        for vehicle_data in vehicles.values():
            for zone_name, visits in vehicle_data['zones'].items():
                for visit in visits:
                    if visit['duration'] is not None:
                        all_dwell_times[zone_name].append(visit['duration'])

    # Videos per camera
    print(f"\nVideos per Camera:")
    for camera, count in sorted(videos_by_camera.items()):
        print(f"  {camera}: {count}")

    # Total vehicles per zone (across all videos)
    print(f"\nTotal Vehicles per Zone (across all videos):")
    for zone, count in sorted(all_zone_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  {zone}: {count}")

    # Overall vehicle class distribution
    print(f"\nOverall Vehicle Class Distribution:")
    total_vehicles = sum(all_class_counts.values())
    for class_name, count in sorted(all_class_counts.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / total_vehicles * 100) if total_vehicles > 0 else 0
        print(f"  {class_name}: {count} ({percentage:.1f}%)")

    # Average dwell time per zone (across all videos)
    print(f"\nAverage Dwell Time per Zone (across all videos):")
    for zone_name, dwell_times in sorted(all_dwell_times.items()):
        if dwell_times:
            avg_dwell = sum(dwell_times) / len(dwell_times)
            min_dwell = min(dwell_times)
            max_dwell = max(dwell_times)
            print(f"  {zone_name}:")
            print(f"    Average: {avg_dwell:.2f}s")
            print(f"    Min: {min_dwell:.2f}s")
            print(f"    Max: {max_dwell:.2f}s")
            print(f"    Total samples: {len(dwell_times)}")

    # Show sample of individual videos
    print(f"\nSample Videos:")
    for video in videos[:5]:
        metadata = video.get('metadata', {})
        summary = video.get('summary', {})
        print(f"  {metadata.get('filename', 'Unknown')} - {summary.get('total_vehicles', 0)} vehicles")


def find_vehicles_by_pattern(data: Dict, zone_sequence: List[str]) -> List[Dict]:
    """Find vehicles that visited zones in a specific sequence"""

    matching_vehicles = []

    # Handle both single video and consolidated formats
    videos_to_check = data.get('videos', [data])

    for video in videos_to_check:
        vehicles = video.get('vehicles', {})
        metadata = video.get('metadata', {})

        for vehicle_id, vehicle_data in vehicles.items():
            zones_visited = list(vehicle_data['zones'].keys())

            # Check if the zone sequence matches (in order)
            if len(zones_visited) >= len(zone_sequence):
                matches = True
                for i, zone in enumerate(zone_sequence):
                    if i >= len(zones_visited) or zones_visited[i] != zone:
                        matches = False
                        break

                if matches:
                    matching_vehicles.append({
                        'video': metadata.get('filename', 'Unknown'),
                        'vehicle_id': vehicle_id,
                        'class_name': vehicle_data['class_name'],
                        'zones': zones_visited
                    })

    return matching_vehicles


def main():
    if len(sys.argv) < 2:
        print("Usage: python analyze_vehicle_durations.py <duration_file.json>")
        print("\nExample:")
        print("  python analyze_vehicle_durations.py vehicle_durations_all.json")
        print("  python analyze_vehicle_durations.py video.durations.json")
        sys.exit(1)

    file_path = Path(sys.argv[1])

    if not file_path.exists():
        print(f"Error: File not found: {file_path}")
        sys.exit(1)

    print(f"Loading duration data from: {file_path}")
    data = load_duration_data(file_path)

    # Determine if this is a single video or consolidated data
    if 'videos' in data and isinstance(data['videos'], list):
        # Consolidated format
        analyze_consolidated_data(data)

        # Show detailed analysis for first video
        if data['videos']:
            analyze_single_video(data['videos'][0])
    else:
        # Single video format
        analyze_single_video(data)

    # Example: Find vehicles that went through specific zones
    print(f"\n{'=' * 70}")
    print(f"Example: Finding vehicles with specific zone patterns")
    print(f"{'=' * 70}")

    # Try to find vehicles that visited 'entry' zone
    # (You can customize this based on your zone names)
    all_zones = set()

    if 'videos' in data:
        for video in data['videos']:
            for vehicle in video.get('vehicles', {}).values():
                all_zones.update(vehicle['zones'].keys())
    else:
        for vehicle in data.get('vehicles', {}).values():
            all_zones.update(vehicle['zones'].keys())

    print(f"\nAll zones found in data: {', '.join(sorted(all_zones))}")

    print(f"\n{'=' * 70}")
    print("Analysis Complete!")
    print(f"{'=' * 70}\n")


if __name__ == "__main__":
    main()
